### PR TITLE
Added low power module

### PR DESCRIPTION
**Pull request by David-OConnor**
Allows entering Sleep, Stop, or Standby modes by calling a function.

### CODE REVIEW

**Comment by David-OConnor** [comment]
Thoughts on why CI is failing for rustfmt?

**Comment by ra-kete** [comment]
> Thoughts on why CI is failing for rustfmt?

If you click on the details of the failed job, you can see rustfmt's suggested diff. In this case, some imports have the wrong order. You can also just run rustfmt on you code locally before committing to prevent something like this in the future (same for clippy).

**Comment by David-OConnor** [comment]
Thanks. I think my local fmt is set up differently.

**Comment by David-OConnor** [comment]
Please merge

**Pull request closed without merging**
