### PR TITLE
Fix delay

### PR DESCRIPTION
**Pull request by David-OConnor**
Delay is inaccurate if you attempt to delay for more than 1<<24 cycles. See [this f4 PR](https://github.com/stm32-rs/stm32l4xx-hal/pull/143) This PR is identical. Props to @jamesmunns for writing this, and helping me on Matrix chat.

### CODE REVIEW

**Comment by Sh3Rm4n** [comment]
Hey just a quick tip: Before you have to close PRs, because you branched from the wrong commit, you can also you [`git rebase`](https://git-scm.com/book/de/v2/Git-Branching-Rebasing) and then force push on your branch. 

(`git rebase --interactiv` is also a really useful command  to cleanup commit histories :) )

**Review by Sh3Rm4n — APPROVED** [review]
LGTM, will merge after commit cleanup :)

**Comment by David-OConnor** [comment]
Thanks for the tip on rebase. I'll check out the interaction flag. I've been extra struggling with rebase lately due to merge conflicts in `cargo.toml`.

**Comment by strom-und-spiele** [comment]
@Sh3Rm4n once did a nice introduction on rebase for me. I summed it up in my personal documentation and am willing to clutter this PR with the totally unrelated information. here you go:
# reabse

## select new base

Option 1: see the logs (`git log --all --decorate --oneline --graph`) for the commit hash to rebase to and call `git rebase -i <hash>`

Option 2: rebase to a known branch (e.g. master) `git rebase -i master`

## select targets

Your editor opens. See the text at the end on how to select different commits. On exiting the editor, git attempts to rebase the script.
If everything works, you’re done :tada: 

If not:

## resolve the conflicts step by step

See the conflict: `git diff` will print the filename. Let's say it's /PATH/TO/FILE

### Option A: You simply want to pic an existing one

`git checkout --SELECTION /PATH/TO/FILE` 
where SELECTION is
1. `--ours` if the solution from the base branch is what you want
2. `--theirs` if the solution from the fork is what you want

### Option B: Manual modifications are needed

Edit the file like you normally would

### continue
```
git add /PATH/TO/FILE
git rebase --continue
```

---
This is by no means exhaustive, but it helps me a lot when I'm rebase'ing once a month

**Pull request closed without merging**
