### PR TITLE
Implement InputPin GPIO traits

### PR DESCRIPTION
**Pull request by manuel-woelker**
Based on the original pull request by @octycs

cf. https://github.com/japaric/stm32f30x-hal/pull/16

Let me know if you have any feedback

### CODE REVIEW

**Comment by dfrankland** [comment]
@manuel-woelker similar to the other PR, do you think it would be good to use the `unproven` feature flag?

**Comment by manuel-woelker** [comment]
Whoops, I thought I remembered the InputPin losing unproven, but alas not yet...

I added the unproven feature flag, and added a dependency on "embedded-hal/unproven"

**Comment by dfrankland** [comment]
Looks great! Thanks for the PR.

**Comment by dfrankland** [comment]
I just tested this out and it works great :smile: so exciting!

**Pull request merged**
