### PR TITLE
Fix I2C clock and support I2C3

### PR DESCRIPTION
**Pull request by Piroro-hs**
* Fix I2C clock
  STM32F3 I2C peripherals are clocked by HSI or sysclk, not pclk1

* Support I2C3
  I2C3 is available on f301, f318, f302x6/8/d/e, f303xd/e and f398
  Also remove I2C2 support on f303x6/8 and f328

* Move I2C implementation out of macro
  The big `i2c!` macro makes code less readable and confuses rustfmt, clippy, etc.
  Inspired by f7xx-hal

### CODE REVIEW

**Comment by Piroro-hs** [comment]
Clippy failed on rtc.rs...

**Comment by David-OConnor** [comment]
I can add this to my fork and its crate if you'd like.

**Comment by Sh3Rm4n** [comment]
I'll finally look at this tomorrow or at least until the end of the week :)

**Review by Sh3Rm4n — APPROVED** [review]
Thanks for the I2C improvements! 
LGTM. 

I trust you, with the device feature guards. 
~~As this extends the supported I2C devices a CHANGELOG entry would be welcome! :) ~~

EDIT: Should have looked closly. You have added everything to the changelog already 🙈 

However I've one question: 

This struct is now the new instace:

https://github.com/stm32-rs/stm32f3xx-hal/blob/c0aed1ac3cbcdbad025d5d76e9ae165ce4bf09bf/src/i2c.rs#L78-L82

Which gets passed as a parameter to the `new` method?

https://github.com/stm32-rs/stm32f3xx-hal/blob/c0aed1ac3cbcdbad025d5d76e9ae165ce4bf09bf/src/i2c.rs#L110

which returns the same instance? How to even create the instance passed towards `I2C::new()`

I'm a bit confused how to use this module now. And when do we now, we create a  `I2C1`, `I2C2`  or `I2C3` instance?
Could you explain this part to me? Or even better. Add a working example or at least a brief documentation ontop of this module :)

**Comment by Sh3Rm4n** [comment]
I rebased your branch to resolve the conflicts:

This is the relevant diff of i2c.rs:

<details>

```patch
diff --git a/src/i2c.rs b/src/i2c.rs
index 80c1fa3..3f932d4 100644
--- a/src/i2c.rs
+++ b/src/i2c.rs
@@ -1,5 +1,6 @@
 //! Inter-Integrated Circuit (I2C) bus
 
+use core::convert::TryFrom;
 use core::ops::Deref;
 
 use crate::{
@@ -19,7 +20,6 @@ use crate::{
     pac::I2C3,
 };
 
-use cast::u8;
 use cfg_if::cfg_if;
 
 /// I2C error
@@ -167,22 +167,25 @@ impl<I2C, SCL, SDA> I2c<I2C, (SCL, SDA)> {
             (presc, scll, sclh, sdadel, scldel)
         };
 
-        let presc = u8(presc).unwrap();
         assert!(presc < 16);
-        let scldel = u8(scldel).unwrap();
         assert!(scldel < 16);
-        let sdadel = u8(sdadel).unwrap();
         assert!(sdadel < 16);
-        let sclh = u8(sclh).unwrap();
-        let scll = u8(scll).unwrap();
+        let sclh = u8::try_from(sclh).unwrap();
+        let scll = u8::try_from(scll).unwrap();
 
+        // Configure for "fast mode" (400 KHz)
         // NOTE(write): writes all non-reserved bits.
         i2c.timingr.write(|w| {
-            w.presc().bits(presc);
-            w.scll().bits(scll);
-            w.sclh().bits(sclh);
-            w.sdadel().bits(sdadel);
-            w.scldel().bits(scldel)
+            w.presc()
+                .bits(presc as u8)
+                .sdadel()
+                .bits(sdadel as u8)
+                .scldel()
+                .bits(scldel as u8)
+                .scll()
+                .bits(scll)
+                .sclh()
+                .bits(sclh)
         });
 
         // Enable the peripheral

```

</details>

I've backuped your old branch to [my fork](https://github.com/Sh3Rm4n/stm32f3xx-hal/tree/i2c-fix-clock-i2c3-backup)

**Comment by Piroro-hs** [comment]
Example added!

The first argument of `I2c::<I2C, PINS>::new()`is `i2c: I2C` where `I2C: Instance`, and we `impl Instance for $I2CX` inside the macro. So it accepts `pac::{I2C1, I2C2, I2C3}` and usage of `I2c::new()` is not changed from `I2c::i2c1()` and  `I2c::i2c2()`.

**Review by Sh3Rm4n — APPROVED** [review]
Nice. With example, this is much clearer and finally makes sense to me 😅 

I like this change. LGTM and thanks for this PR!

**Pull request merged**
