### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by Sh3Rm4n**

### CODE REVIEW

**Comment by Sh3Rm4n** [comment]
As soon as we merged https://github.com/stm32-rs/stm32f3xx-hal/pull/35 and maybe https://github.com/stm32-rs/stm32f3xx-hal/pull/39 we should release a new version, as many features were added since the last change.

**Comment by dfrankland** [comment]
I am in agreement. It would be great to get #35 and #39 in before bumping :+1:

**Comment by Sh3Rm4n** [comment]
I've merged the other PR's. So this is ready to be merged and published to
`crates.io`. :)

**Comment by dfrankland** [comment]
Tagged and published :+1: Thanks for all of your help!

**Comment by Sh3Rm4n** [comment]
You are welcome! And thank you very much for your assistance, code review and
checking for regression on hardware!

**Comment by strom-und-spiele** [comment]
Thanks for your work.

I noticed that the new documentation could not be built due to 
```
[INFO] [stderr]     Checking stable_deref_trait v1.1.1
[INFO] [stderr] error[E0463]: can't find crate for `core`
[INFO] [stderr]   |
[INFO] [stderr]   = note: the `thumbv7em-none-eabihf` target may not be installed
```
[Full Error Log](https://docs.rs/crate/stm32f3xx-hal/0.4.0/builds/208401)

Not sure how to help with this.

**Comment by Sh3Rm4n** [comment]
Yeah noticed this too. I guess this has something to do, that docs.rs does not build the docs for every target anymore. 

I've read about, that setting the default build target in .cargo/config could help. But I've not investigated further.

**Comment by dfrankland** [comment]
Oh yeah, it must be:
https://github.com/stm32-rs/stm32f3xx-hal/blob/7e0d7e67617fdb12174f76872a00bd2f54a6eb01/.cargo/config#L8

**Pull request merged**
