### PR TITLE
Added DAC, low-power, alternate clocks, interrupts module. Added seri…

### PR DESCRIPTION
**Pull request by David-OConnor**
- DAC
- Low-power
- Clocks (Set prescalers instead of speed approach)
- External interrupts
- RTC wakeup, and bugfixes
- Serial example
- Feature additions to timer
- Fix for I2C repeating start

I will no longer manage more than a few branches at a time.

This branch will be published periodically as [stm32f3xx-hal-v2](https://crates.io/crates/stm32f3xx-hal-v2).

### CODE REVIEW

**Comment by Sh3Rm4n** [comment]
Hey, just a heads up, it was not really useful to close all the previous PRs and combine them into one. :) 

I know, that I've kept you waiting and I'll hope, that I've time to review some of these changes. 
They should however be split into separate PRs. 
What I could do, is to cherry pick some of these commits to single out standalone changes. 

Thank you for this PR however, to let us now about your progress on your fork :)

**Comment by David-OConnor** [comment]
I appreciate it. I closed the individual PRs since my limited git skills aren't up to managing them all at once. I'll split off new ones as you're ready to review.

**Comment by Sh3Rm4n** [comment]
Uhh that's cool to hear. 

If you have any questions about git or need help you can reach me via matrix at @sh3rm4n:matrix.org

**Comment by David-OConnor** [comment]
The [L0 RCC hal impl](https://github.com/stm32-rs/stm32l0xx-hal/blob/master/src/rcc.rs) is simlar to the `clocks` module in this fork.

**Comment by David-OConnor** [comment]
Fixed. This was due to none of the STM32 HALs other than H7 supporting repeating start on I2C. Many devices don't care, but some, like this, due. The fix was copy+pasting the `read_write` method from H7's I2C module into L4.

Issue on L4: https://github.com/stm32-rs/stm32l4xx-hal/issues/189
PR on L4: https://github.com/stm32-rs/stm32l4xx-hal/pull/186

**Comment by David-OConnor** [comment]
closed in favor of Closed in favor of https://github.com/David-OConnor/stm32-hal

**Pull request closed without merging**
