### PR TITLE
Implement InputPin for Output<OpenDrain> pins

### LINKED ISSUE #84: Implement InputPin trait for PA1<Output<OpenDrain>>
I'm trying to read a dht11 humidity sensor with a stm32f303 discovery board

the example in the dht11 crate is for stmf0xx boards:
https://github.com/michaelbeaumont/dht-sensor/blob/master/examples/stm32f042.rs#L30

Rather than give in and just buy an stm32f0xx board I'd like to have a crack at adding this trait. If anyone knows that it is futile (eg  `Output<OpenDrain>` is not both `InputPin` and `OutputPin`  for the f3) or not useful in anyway please say so.

Part-converted example: https://gist.github.com/peter-wilkins/b5c914b1f8f5b4098b198133b4280472

I'm just starting out with embedded but will attempt to put together an PR, it may take some time. Any advice appreciated.

### PR DESCRIPTION
**Pull request by ra-kete**
Forked from #105 and added some cleanup.

Resolves #84.
Once this is merged we can close both #88 and #105.

### CODE REVIEW

**Comment by David-OConnor** [comment]
Sweet

**Comment by ra-kete** [comment]
@David-OConnor I'll take that to mean this looks good to you? If so I'll merge tomorrow.

**Comment by David-OConnor** [comment]
Yep!

**Comment by David-OConnor** [comment]
Yep - looks good!

**Pull request merged**
