### PR TITLE
added stm32f302x6, stm32f302x8

### PR DESCRIPTION
**Pull request by sprhawk**

### CODE REVIEW

**Comment by ra-kete** [comment]
This has also been done in #129, but I suppose it will still take some time until that gets merged, so I'm fine with merging this in the meantime.

I'm curious, have you tested the crate with one of these boards?

**Comment by sprhawk** [comment]
@ra-kete Yes, I'm running it on an stm32f302r8

**Review by ra-kete — CHANGES_REQUESTED** [review]
Could you add a changelog entry too?
LGTM otherwise.

**Comment by sprhawk** [comment]
@ra-kete How to write content of Changelog?

Like this?
```
### Added                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
- added stm32f302x6, stm32f302x8 ([#132](https://github.com/stm32-rs/stm32f3xx-hal/pull/132))                                                                                                                                                                                                                           
```

**Comment by ra-kete** [comment]
Yes, just put it under the existing `Added` entries under the `Unreleased` version.
For wording you look at what's there for adding support for new devices in older versions. Something like "Support for `stm32f302x6` and `stm32f302x8` devices".

**Comment by sprhawk** [comment]
@ra-kete added to changelog

**Review by ra-kete — APPROVED** [review]

**Pull request merged**
